### ISSUE TITLE
Unable to download complete build when using --build flag

### ISSUE THREAD

**Issue by erlkoenig91** [jfrog/jfrog-cli#1252]
**Describe the bug**
When trying to download the latest artifacts from Arifactory using Jfrog CLI and specifying the --build option, the Jfrog CLI didn´t find any files to download. Test with older Versions (1.44.0) working and using the Buildnumber /123 working too.  

**To Reproduce**
CI=true jfrog rt dl --url https://linktoartifactoy.com/artifactory --user _deployuser --password ASDFASDFASDFASDFASDF --build application::app-name::trunk '*' "/tmp/download"

{
  "status": "success",
  "totals": {
    "success": 0,
    "failure": 0
  }
}

**Expected behavior**
According to the documentation https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DownloadingFiles, it says when we use --build flag and If we do not specify the build number, the artifacts are filtered by the latest build number. So we are expecting to get the latest artifact version.

CI=true jfrog rt dl --url https://linktoartifactoy.com/artifactory --user _deployuser --password ASDFASDFASDFASDFASDF --build application::app-name::trunk '*' "/tmp/download"

{
  "status": "success",
  "totals": {
    "success": 2,
    "failure": 0
  }
}

**Screenshots**
No Screenshots

**Versions**
- JFrog CLI version: 2.4.1
- JFrog CLI operating system: 1.51.2
- Artifactory Version: 7.25.7

**Additional context**

**Comment by sverdlov93** [comment]
@erlkoenig91 
Thanks for reporting this issue.
It appears that the problem occurs when using build name without build number to get the latest build (or using LATEST parameter) with build name that contains Slash (`:`) character.
Behind the scenes, we escape slashes with `%3A` encoding, but it appears that AQL has a problem resolving the `%` character so the query fails to provide.

Our apologies for the inconvenience caused by this bug.

That issue has the same root cause as https://github.com/jfrog/jfrog-cli/issues/1220.
Resolving that issue requires changes on both Artifactory and JFrog CLI.
We will share an update here once the fix is released.
We opened https://www.jfrog.com/jira/browse/RTFACT-25808 to track the required fix on Artifactory’s side.

**Comment by Zoz24** [comment]
> Reference in ne

https://jfrog.atlassian.net/browse/RTFACT-25808 is marked as closed but the this problem persists:
https://github.com/jfrog/jfrog-cli/issues/1220
