### ISSUE TITLE
Support for Artifactory Docker promotion API

### ISSUE THREAD

**Issue by jghal** [jfrog/jfrog-cli#678]
Artifactory has a nice REST API call for promoting a docker image between repositories, allowing me the change the image tag in the process.

https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-PromoteDockerImage

While I know that the jfrog-cli has support for a different workflow [here](https://jfrog.com/blog/manage-your-docker-builds-with-jfrog-cli-in-5-easy-steps/) where I add build info to a Docker image across build and release/promote CI stages

``
jfrog rt docker-pull 
jfrog rt build-publish
``

and

```
jfrog rt build-promote
```

I tried to test this out and the build-promote failed saying it can't find the artifacts of the build. But honestly I would just prefer having a `docker-promote` command that calls the existing API. 

```
jfrog rt docker-promote <repoKey> <dockerRepository>:<tag> <targetDockerRepository> [<targetTag>] [--copy]
```

I like being able to specify a target tag and dislike the spurious forcing of the Build feature on a workflow that doesn't really require it.

**Comment by jghal** [comment]
Here's the error I'm seeing with attempting to use the build-publish/build-promote workflow

```
$ docker pull docker.bintray.io/jfrog/jfrog-cli-go:1.35.3 
1.35.3: Pulling from jfrog/jfrog-cli-go
Digest: sha256:63149fb84911280ed10a810c33bc89323b1c618cc9b0c437069c02f54881263b
Status: Image is up to date for docker.bintray.io/jfrog/jfrog-cli-go:1.35.3
docker.bintray.io/jfrog/jfrog-cli-go:1.35.3
$ docker tag docker.bintray.io/jfrog/jfrog-cli-go:1.35.3 devops-docker.repo.example.com/jfrog-cli-go:1.35.3 
$ jfrog rt docker-push devops-docker.repo.example.com/jfrog-cli-go:1.35.3 devops-docker-snapshots --build-name jfrog-cli --build-number 1
WARNING! Your password will be stored unencrypted in /home/hbl4218/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
The push refers to repository [devops-docker.repo.example.com/jfrog-cli-go]
0135afc59e01: Pushed 
8820917f39dd: Pushed 
3fc64803ca2d: Layer already exists 
1.35.3: digest: sha256:63149fb84911280ed10a810c33bc89323b1c618cc9b0c437069c02f54881263b size: 1161
[Info] Setting properties...
[Info] [Thread 1] Setting properties on: devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__5d20c808ce198565ff70b3ed23a991dd49afac45dece63474b27ce6ed036adc6
[Info] [Thread 2] Setting properties on: devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__cd52e8cea908fa2be9a148d31ffcff54d1c515d1db4a6fbf2a8a3507450fc791
[Info] [Thread 0] Setting properties on: devops-docker-snapshots/jfrog-cli-go/1.35.3/manifest.json
[Info] [Thread 2] Setting properties on: devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__475a77d520eff53794bea7b3ba4d61a23a0c33e0587b74a96a356439cc14ef41
[Info] [Thread 1] Setting properties on: devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__b4f1e96eee44bd68078db7389a540f4af34d557198332542062def8275d02b8b
[Info] [Thread 0] Setting properties on: devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__b4f1e96eee44bd68078db7389a540f4af34d557198332542062def8275d02b8b
[Info] Done setting properties.
$ jfrog rt bp jfrog-cli 1
[Info] Deploying build info...
[Info] Build info successfully deployed. Browse it in Artifactory under https://repo.example.com/artifactory/webapp/builds/jfrog-cli/1
$ JFROG_CLI_LOG_LEVEL=ERROR jfrog rt s devops-docker --build jfrog-cli/1 | jq -r '.[].path'
devops-docker-snapshots/jfrog-cli-go/1.35.3/manifest.json
devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__5d20c808ce198565ff70b3ed23a991dd49afac45dece63474b27ce6ed036adc6
devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__475a77d520eff53794bea7b3ba4d61a23a0c33e0587b74a96a356439cc14ef41
devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__cd52e8cea908fa2be9a148d31ffcff54d1c515d1db4a6fbf2a8a3507450fc791
devops-docker-snapshots/jfrog-cli-go/1.35.3/sha256__b4f1e96eee44bd68078db7389a540f4af34d557198332542062def8275d02b8b
$ JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt bpr jfrog-cli 1 devops-docker-staging
[Debug] Usage Report: Sending info...
[Info] Promoting build...
[Debug] Sending HTTP POST request to: https://repo.example.com/artifactory/api/build/promote/jfrog-cli/1
[Debug] Sending HTTP GET request to: https://repo.example.com/artifactory/api/system/version
[Debug] The Artifactory version is: 6.10.1
[Debug] Sending HTTP POST request to: https://repo.example.com/artifactory/api/system/usage
[Debug] Usage Report: Artifactory response: 200 OK
[Debug] Usage Report: Usage info sent successfully.
[Error] Artifactory response: 400 Bad Request
{
  "errors": [
    {
      "status": 400,
      "message": "Unable to find artifacts of build 'jfrog-cli' #1: aborting promotion."
    }
  ]
}
```

**Comment by eyalbe4** [comment]
@jghal,

Thank you for reporting this issue and requesting this feature request.
Adding the new command seems like a good idea and we'll add it to our roadmap.

As for the issue you reported, we're looking into it right now and we'll report our findings here.

BTW - you can already invoke the *api/docker/-repoKey-/v2/promote* REST API with the *jfrog rt curl* command.

**Comment by jghal** [comment]
Thanks @eyalb4doc!

I did find the _curl_ subcommand over the weekend and I have to say it's pretty nifty and it does unblock from using the jfrog/jfrog-cli-go Docker image in my pipelines. But I would still prefer the native subcommand because it can get pretty tricky to properly quote/escape raw JSON in a YAML file (which is the pipeline definition language du jour).

**Comment by Or-Gabay** [comment]
@jghal, I have created a fix for this bug https://github.com/jfrog/jfrog-cli/pull/685
Docker manifest may contain duplicate layers such as `jfrog-cli-go:1.35.3` image, by promoting that image, Artifactory started to promote each layer and failed to locate the duplicate layers which exist only once.
As a result, a bad request was returned

**Comment by Or-Gabay** [comment]
@jghal, we released JFrog CLI v1.35.4 to resolve this issue.
Feel free to upgrade - We'll appreciate your feedback for that!

**Comment by jghal** [comment]
Thanks @Or-Gabay, will try it out.

Regarding the `jfrog rt curl` option to calling the docker promotion API, I found that it depends on there being a curl executable, and the jfrog/jfrog-cli-go Docker image lacks that (and also jq to parse json API responses), so still having a sub-command in jfrog-cli-go to call the API will be beneficial (I may file a feature request to add curl and jq to the official jfrog-cli-go Docker image too).

**Comment by jghal** [comment]
I appear to have long forgotten to report back here. The `docker-promote` command is working as desired (and also the current jfrog-cli-go Docker image has the curl executable added by now too).
